version: '2'

services:
  hydra:
    image: oryd/hydra:v0.10.0-alpha.21
    networks:
      - subnet
    ports:
      - "4444:4444"
      - "4445:4445"
    environment:
      - CONSENT_URL=http://localhost:4446/auth/consent
      - DATABASE_URL=memory
      - FORCE_ROOT_CLIENT_CREDENTIALS=root:secret
      - ISSUER=http://localhost:4444/
      - LOG_LEVEL=debug
    restart: unless-stopped
    command: "host --dangerous-force-http"

  consent-app:
    build:
      context: example/
      dockerfile: Dockerfile
    environment:
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CALLBACK_URL=http://localhost:6001/auth/callback

    networks:
      - subnet
    ports:
      - "4446:3000"

networks:
  subnet:
    driver: bridge
