// flow-typed signature: fa3711f9f88bf7a0bbda50effd498bcc
// flow-typed version: <<STUB>>/chargebee_v^2.1.9/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chargebee'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chargebee' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chargebee/lib/chargebee' {
  declare module.exports: any;
}

declare module 'chargebee/lib/resources/api_endpoints' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chargebee/lib/chargebee.js' {
  declare module.exports: $Exports<'chargebee/lib/chargebee'>;
}
declare module 'chargebee/lib/resources/api_endpoints.js' {
  declare module.exports: $Exports<'chargebee/lib/resources/api_endpoints'>;
}
