// flow-typed signature: 7142831104335f8040a99cdc5f4c5680
// flow-typed version: <<STUB>>/connect-ensure-login_v^0.1.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-ensure-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-ensure-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-ensure-login/lib/ensureLoggedIn' {
  declare module.exports: any;
}

declare module 'connect-ensure-login/lib/ensureLoggedOut' {
  declare module.exports: any;
}

declare module 'connect-ensure-login/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-ensure-login/lib/ensureLoggedIn.js' {
  declare module.exports: $Exports<'connect-ensure-login/lib/ensureLoggedIn'>;
}
declare module 'connect-ensure-login/lib/ensureLoggedOut.js' {
  declare module.exports: $Exports<'connect-ensure-login/lib/ensureLoggedOut'>;
}
declare module 'connect-ensure-login/lib/index.js' {
  declare module.exports: $Exports<'connect-ensure-login/lib/index'>;
}
