// flow-typed signature: 42714e2b8b3002f0e166f55449b8fdbc
// flow-typed version: <<STUB>>/hydra-js_v~0.1.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hydra-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hydra-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hydra-js/hydra' {
  declare module.exports: any;
}

declare module 'hydra-js/hydra.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hydra-js/hydra.js' {
  declare module.exports: $Exports<'hydra-js/hydra'>;
}
declare module 'hydra-js/hydra.test.js' {
  declare module.exports: $Exports<'hydra-js/hydra.test'>;
}
