// flow-typed signature: 6c83ffc2b8495b90a0e72b457e304084
// flow-typed version: <<STUB>>/jwk-to-pem_v~1.2.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jwk-to-pem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jwk-to-pem' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jwk-to-pem/src/b64-to-bn' {
  declare module.exports: any;
}

declare module 'jwk-to-pem/src/ec' {
  declare module.exports: any;
}

declare module 'jwk-to-pem/src/jwk-to-pem' {
  declare module.exports: any;
}

declare module 'jwk-to-pem/src/rsa' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jwk-to-pem/src/b64-to-bn.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/b64-to-bn'>;
}
declare module 'jwk-to-pem/src/ec.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/ec'>;
}
declare module 'jwk-to-pem/src/jwk-to-pem.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/jwk-to-pem'>;
}
declare module 'jwk-to-pem/src/rsa.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/rsa'>;
}
