// flow-typed signature: daa9ae47d848394ca3dcfaa4e0f51196
// flow-typed version: <<STUB>>/ory-hydra-sdk_v~0.10.0-alpha.7/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-hydra-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-hydra-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/HealthApi' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/JsonWebKeyApi' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/OAuth2Api' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/PolicyApi' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/WardenApi' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/ApiClient' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/index' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestAcceptance' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestManager' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestRejection' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Context' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Firewall' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Group' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/GroupMembers' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Handler' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse200' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse2001' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse401' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JoseWebKeySetRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKey' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySet' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySetGeneratorRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/KeyGenerator' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Manager' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2Client' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2ConsentRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2TokenIntrospection' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Policy' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/PolicyConditions' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/RawMessage' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerAcceptConsentRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerCreatePolicyParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowAccessRequestParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowTokenAccessRequestParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerGetPolicyParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJsonWebKeyQuery' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkCreateSet' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkSetQuery' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSet' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSetKey' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequestPayload' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponseBody' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRejectConsentRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRevokeOAuth2TokenParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerUpdatePolicyParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenAccessRequestResponseParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenTokenAccessRequestResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/TokenAllowedRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequestResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequestResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WellKnown' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Writer' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/api/HealthApi.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/api/JsonWebKeyApi.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/api/OAuth2Api.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/api/PolicyApi.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/api/WardenApi.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequestAcceptance.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequestManager.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequestRejection.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Context.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Firewall.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Group.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/GroupMembers.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Handler.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/InlineResponse200.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/InlineResponse2001.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/InlineResponse401.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/JoseWebKeySetRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/JsonWebKey.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/JsonWebKeySet.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/JsonWebKeySetGeneratorRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/KeyGenerator.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Manager.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/OAuth2Client.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/OAuth2consentRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/OAuth2TokenIntrospection.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Policy.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/PolicyConditions.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/RawMessage.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerAcceptConsentRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerCreatePolicyParameters.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerDoesWardenAllowAccessRequestParameters.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerDoesWardenAllowTokenAccessRequestParameters.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerGetPolicyParameters.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJsonWebKeyQuery.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkCreateSet.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkSetQuery.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkUpdateSet.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkUpdateSetKey.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerListPolicyParameters.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerListPolicyResponse.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthConsentRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthConsentRequestPayload.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthIntrospectionRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthIntrospectionResponse.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthTokenResponse.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthTokenResponseBody.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerRejectConsentRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerRevokeOAuth2TokenParameters.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerUpdatePolicyParameters.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerWardenAccessRequestResponseParameters.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerWardenTokenAccessRequestResponse.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/TokenAllowedRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/WardenAccessRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/WardenAccessRequestResponse.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/WardenTokenAccessRequest.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/WardenTokenAccessRequestResponse.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/WellKnown.spec' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Writer.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/HealthApi.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/api/HealthApi'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/JsonWebKeyApi.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/api/JsonWebKeyApi'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/OAuth2Api.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/api/OAuth2Api'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/PolicyApi.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/api/PolicyApi'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/WardenApi.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/api/WardenApi'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/ApiClient.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/ApiClient'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/index.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/index'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestAcceptance.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestAcceptance'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestManager.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestManager'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestRejection.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestRejection'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Context.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Context'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Firewall.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Firewall'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Group.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Group'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/GroupMembers.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/GroupMembers'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Handler.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Handler'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse200.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse200'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse2001.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse2001'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse401.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse401'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JoseWebKeySetRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/JoseWebKeySetRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKey.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKey'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySet.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySet'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySetGeneratorRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySetGeneratorRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/KeyGenerator.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/KeyGenerator'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Manager.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Manager'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2Client.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2Client'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2ConsentRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2ConsentRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2TokenIntrospection.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2TokenIntrospection'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Policy.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Policy'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/PolicyConditions.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/PolicyConditions'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/RawMessage.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/RawMessage'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerAcceptConsentRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerAcceptConsentRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerCreatePolicyParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerCreatePolicyParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowAccessRequestParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowAccessRequestParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowTokenAccessRequestParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowTokenAccessRequestParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerGetPolicyParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerGetPolicyParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJsonWebKeyQuery.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJsonWebKeyQuery'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkCreateSet.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkCreateSet'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkSetQuery.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkSetQuery'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSet.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSet'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSetKey.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSetKey'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequestPayload.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequestPayload'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponseBody.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponseBody'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRejectConsentRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRejectConsentRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRevokeOAuth2TokenParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRevokeOAuth2TokenParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerUpdatePolicyParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerUpdatePolicyParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenAccessRequestResponseParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenAccessRequestResponseParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenTokenAccessRequestResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenTokenAccessRequestResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/TokenAllowedRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/TokenAllowedRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequestResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequestResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequestResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequestResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WellKnown.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/WellKnown'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Writer.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Writer'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/api/HealthApi.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/api/HealthApi.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/api/JsonWebKeyApi.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/api/JsonWebKeyApi.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/api/OAuth2Api.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/api/OAuth2Api.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/api/PolicyApi.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/api/PolicyApi.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/api/WardenApi.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/api/WardenApi.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequestAcceptance.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequestAcceptance.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequestManager.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequestManager.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequestRejection.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/ConsentRequestRejection.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Context.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/Context.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Firewall.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/Firewall.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Group.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/Group.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/GroupMembers.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/GroupMembers.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Handler.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/Handler.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/InlineResponse200.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/InlineResponse200.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/InlineResponse2001.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/InlineResponse2001.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/InlineResponse401.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/InlineResponse401.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/JoseWebKeySetRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/JoseWebKeySetRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/JsonWebKey.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/JsonWebKey.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/JsonWebKeySet.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/JsonWebKeySet.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/JsonWebKeySetGeneratorRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/JsonWebKeySetGeneratorRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/KeyGenerator.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/KeyGenerator.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Manager.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/Manager.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/OAuth2Client.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/OAuth2Client.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/OAuth2consentRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/OAuth2consentRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/OAuth2TokenIntrospection.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/OAuth2TokenIntrospection.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Policy.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/Policy.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/PolicyConditions.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/PolicyConditions.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/RawMessage.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/RawMessage.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerAcceptConsentRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerAcceptConsentRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerCreatePolicyParameters.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerCreatePolicyParameters.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerDoesWardenAllowAccessRequestParameters.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerDoesWardenAllowAccessRequestParameters.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerDoesWardenAllowTokenAccessRequestParameters.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerDoesWardenAllowTokenAccessRequestParameters.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerGetPolicyParameters.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerGetPolicyParameters.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJsonWebKeyQuery.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJsonWebKeyQuery.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkCreateSet.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkCreateSet.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkSetQuery.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkSetQuery.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkUpdateSet.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkUpdateSet.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkUpdateSetKey.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerJwkUpdateSetKey.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerListPolicyParameters.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerListPolicyParameters.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerListPolicyResponse.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerListPolicyResponse.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthConsentRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthConsentRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthConsentRequestPayload.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthConsentRequestPayload.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthIntrospectionRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthIntrospectionRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthIntrospectionResponse.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthIntrospectionResponse.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthTokenResponse.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthTokenResponse.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthTokenResponseBody.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerOAuthTokenResponseBody.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerRejectConsentRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerRejectConsentRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerRevokeOAuth2TokenParameters.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerRevokeOAuth2TokenParameters.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerUpdatePolicyParameters.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerUpdatePolicyParameters.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerWardenAccessRequestResponseParameters.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerWardenAccessRequestResponseParameters.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerWardenTokenAccessRequestResponse.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/SwaggerWardenTokenAccessRequestResponse.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/TokenAllowedRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/TokenAllowedRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/WardenAccessRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/WardenAccessRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/WardenAccessRequestResponse.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/WardenAccessRequestResponse.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/WardenTokenAccessRequest.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/WardenTokenAccessRequest.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/WardenTokenAccessRequestResponse.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/WardenTokenAccessRequestResponse.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/WellKnown.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/WellKnown.spec'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/test/model/Writer.spec.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/test/model/Writer.spec'>;
}
