// flow-typed signature: f58ca267ef3725abf97c593c12deea0d
// flow-typed version: <<STUB>>/auth0_v~2.8.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auth0/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'auth0/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'auth0/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'auth0/scripts/changelog' {
  declare module.exports: any;
}

declare module 'auth0/scripts/cleanup' {
  declare module.exports: any;
}

declare module 'auth0/scripts/jsdocs' {
  declare module.exports: any;
}

declare module 'auth0/scripts/prepare' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/DatabaseAuthenticator' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/index' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/OAuthAuthenticator' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/PasswordlessAuthenticator' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/TokensManager' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/UsersManager' {
  declare module.exports: any;
}

declare module 'auth0/src/Auth0RestClient' {
  declare module.exports: any;
}

declare module 'auth0/src/index' {
  declare module.exports: any;
}

declare module 'auth0/src/management/BlacklistedTokensManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/ClientGrantsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/ClientsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/ConnectionsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/DeviceCredentialsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/EmailProviderManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/index' {
  declare module.exports: any;
}

declare module 'auth0/src/management/JobsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/LogsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/ManagementTokenProvider' {
  declare module.exports: any;
}

declare module 'auth0/src/management/ResourceServersManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/RulesManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/StatsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/TenantManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/TicketsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/UsersManager' {
  declare module.exports: any;
}

declare module 'auth0/src/utils' {
  declare module.exports: any;
}

declare module 'auth0/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auth0/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'auth0/docs/scripts/linenumber'>;
}
declare module 'auth0/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'auth0/docs/scripts/prettify/lang-css'>;
}
declare module 'auth0/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'auth0/docs/scripts/prettify/prettify'>;
}
declare module 'auth0/scripts/changelog.js' {
  declare module.exports: $Exports<'auth0/scripts/changelog'>;
}
declare module 'auth0/scripts/cleanup.js' {
  declare module.exports: $Exports<'auth0/scripts/cleanup'>;
}
declare module 'auth0/scripts/jsdocs.js' {
  declare module.exports: $Exports<'auth0/scripts/jsdocs'>;
}
declare module 'auth0/scripts/prepare.js' {
  declare module.exports: $Exports<'auth0/scripts/prepare'>;
}
declare module 'auth0/src/auth/DatabaseAuthenticator.js' {
  declare module.exports: $Exports<'auth0/src/auth/DatabaseAuthenticator'>;
}
declare module 'auth0/src/auth/index.js' {
  declare module.exports: $Exports<'auth0/src/auth/index'>;
}
declare module 'auth0/src/auth/OAuthAuthenticator.js' {
  declare module.exports: $Exports<'auth0/src/auth/OAuthAuthenticator'>;
}
declare module 'auth0/src/auth/PasswordlessAuthenticator.js' {
  declare module.exports: $Exports<'auth0/src/auth/PasswordlessAuthenticator'>;
}
declare module 'auth0/src/auth/TokensManager.js' {
  declare module.exports: $Exports<'auth0/src/auth/TokensManager'>;
}
declare module 'auth0/src/auth/UsersManager.js' {
  declare module.exports: $Exports<'auth0/src/auth/UsersManager'>;
}
declare module 'auth0/src/Auth0RestClient.js' {
  declare module.exports: $Exports<'auth0/src/Auth0RestClient'>;
}
declare module 'auth0/src/index.js' {
  declare module.exports: $Exports<'auth0/src/index'>;
}
declare module 'auth0/src/management/BlacklistedTokensManager.js' {
  declare module.exports: $Exports<'auth0/src/management/BlacklistedTokensManager'>;
}
declare module 'auth0/src/management/ClientGrantsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/ClientGrantsManager'>;
}
declare module 'auth0/src/management/ClientsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/ClientsManager'>;
}
declare module 'auth0/src/management/ConnectionsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/ConnectionsManager'>;
}
declare module 'auth0/src/management/DeviceCredentialsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/DeviceCredentialsManager'>;
}
declare module 'auth0/src/management/EmailProviderManager.js' {
  declare module.exports: $Exports<'auth0/src/management/EmailProviderManager'>;
}
declare module 'auth0/src/management/index.js' {
  declare module.exports: $Exports<'auth0/src/management/index'>;
}
declare module 'auth0/src/management/JobsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/JobsManager'>;
}
declare module 'auth0/src/management/LogsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/LogsManager'>;
}
declare module 'auth0/src/management/ManagementTokenProvider.js' {
  declare module.exports: $Exports<'auth0/src/management/ManagementTokenProvider'>;
}
declare module 'auth0/src/management/ResourceServersManager.js' {
  declare module.exports: $Exports<'auth0/src/management/ResourceServersManager'>;
}
declare module 'auth0/src/management/RulesManager.js' {
  declare module.exports: $Exports<'auth0/src/management/RulesManager'>;
}
declare module 'auth0/src/management/StatsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/StatsManager'>;
}
declare module 'auth0/src/management/TenantManager.js' {
  declare module.exports: $Exports<'auth0/src/management/TenantManager'>;
}
declare module 'auth0/src/management/TicketsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/TicketsManager'>;
}
declare module 'auth0/src/management/UsersManager.js' {
  declare module.exports: $Exports<'auth0/src/management/UsersManager'>;
}
declare module 'auth0/src/utils.js' {
  declare module.exports: $Exports<'auth0/src/utils'>;
}
declare module 'auth0/webpack.config.js' {
  declare module.exports: $Exports<'auth0/webpack.config'>;
}
