// flow-typed signature: 95505a431748a926c845a47e79f61f47
// flow-typed version: <<STUB>>/ory-hydra-sdk_v^0.10.0-alpha.21/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-hydra-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-hydra-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/HealthApi' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/JsonWebKeyApi' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/OAuth2Api' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/PolicyApi' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/WardenApi' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/ApiClient' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/index' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestAcceptance' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestManager' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestRejection' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Context' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Firewall' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Group' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/GroupMembers' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Handler' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse200' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse2001' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse401' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JoseWebKeySetRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKey' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySet' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySetGeneratorRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/KeyGenerator' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Manager' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2Client' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2ConsentRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2TokenIntrospection' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Policy' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/PolicyConditions' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/RawMessage' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerAcceptConsentRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerCreatePolicyParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowAccessRequestParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowTokenAccessRequestParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerGetPolicyParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJsonWebKeyQuery' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkCreateSet' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkSetQuery' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSet' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSetKey' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequestPayload' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponseBody' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRejectConsentRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRevokeOAuth2TokenParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerUpdatePolicyParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenAccessRequestResponseParameters' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenTokenAccessRequestResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/TokenAllowedRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequestResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequest' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequestResponse' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WellKnown' {
  declare module.exports: any;
}

declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/HealthApi.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/api/HealthApi'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/JsonWebKeyApi.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/api/JsonWebKeyApi'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/OAuth2Api.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/api/OAuth2Api'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/PolicyApi.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/api/PolicyApi'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/api/WardenApi.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/api/WardenApi'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/ApiClient.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/ApiClient'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/index.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/index'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestAcceptance.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestAcceptance'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestManager.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestManager'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestRejection.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/ConsentRequestRejection'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Context.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Context'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Firewall.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Firewall'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Group.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Group'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/GroupMembers.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/GroupMembers'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Handler.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Handler'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse200.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse200'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse2001.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse2001'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse401.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/InlineResponse401'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JoseWebKeySetRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/JoseWebKeySetRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKey.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKey'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySet.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySet'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySetGeneratorRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/JsonWebKeySetGeneratorRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/KeyGenerator.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/KeyGenerator'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Manager.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Manager'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2Client.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2Client'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2ConsentRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2ConsentRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2TokenIntrospection.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/OAuth2TokenIntrospection'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Policy.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Policy'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/PolicyConditions.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/PolicyConditions'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/RawMessage.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/RawMessage'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerAcceptConsentRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerAcceptConsentRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerCreatePolicyParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerCreatePolicyParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowAccessRequestParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowAccessRequestParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowTokenAccessRequestParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerDoesWardenAllowTokenAccessRequestParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerGetPolicyParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerGetPolicyParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJsonWebKeyQuery.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJsonWebKeyQuery'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkCreateSet.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkCreateSet'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkSetQuery.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkSetQuery'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSet.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSet'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSetKey.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerJwkUpdateSetKey'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerListPolicyResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequestPayload.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthConsentRequestPayload'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthIntrospectionResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponseBody.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerOAuthTokenResponseBody'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRejectConsentRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRejectConsentRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRevokeOAuth2TokenParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerRevokeOAuth2TokenParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerUpdatePolicyParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerUpdatePolicyParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenAccessRequestResponseParameters.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenAccessRequestResponseParameters'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenTokenAccessRequestResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/SwaggerWardenTokenAccessRequestResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/TokenAllowedRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/TokenAllowedRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequestResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/WardenAccessRequestResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequest.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequest'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequestResponse.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/WardenTokenAccessRequestResponse'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/WellKnown.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/WellKnown'>;
}
declare module 'ory-hydra-sdk/sdk/js/swagger/src/model/Writer.js' {
  declare module.exports: $Exports<'ory-hydra-sdk/sdk/js/swagger/src/model/Writer'>;
}
