// flow-typed signature: c9ae48796d99e053ed50b15183292b97
// flow-typed version: <<STUB>>/superagent-auth-bearer_v0.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-auth-bearer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-auth-bearer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'superagent-auth-bearer/index' {
  declare module.exports: $Exports<'superagent-auth-bearer'>;
}
declare module 'superagent-auth-bearer/index.js' {
  declare module.exports: $Exports<'superagent-auth-bearer'>;
}
