// flow-typed signature: d36f85ce0c89be02cf9541c7e86a8cc5
// flow-typed version: <<STUB>>/url-join_v~2.0.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-join'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-join' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-join/lib/url-join' {
  declare module.exports: any;
}

declare module 'url-join/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-join/lib/url-join.js' {
  declare module.exports: $Exports<'url-join/lib/url-join'>;
}
declare module 'url-join/test/tests.js' {
  declare module.exports: $Exports<'url-join/test/tests'>;
}
